### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by xinyueyuanAmy** [ariacom/Seal-Report#107]
Chinese language support for reports does not work, the following settings have been made
1. Put the Chinese resource package (Translations.zh.csv) in the site's Repository\Settings directory under the following
2, C:\wwwroot\SealReport\Repository\Settings
3, then in the report home page configuration: Culture for Chinese (China)
Could you provide some guidance? Thank you for your help

**Comment by ariacom** [comment]
I made a quick test on the demo site and it seems to work:
![image](https://github.com/ariacom/Seal-Report/assets/12451331/80ba0384-a935-4c99-a7ca-8a499faa2cda)

![image](https://github.com/ariacom/Seal-Report/assets/12451331/82a693ec-52f8-44eb-a3c1-f2966d091702)

**Comment by xinyueyuanAmy** [comment]
Could you provide me the CSV file of translation？

**Comment by ariacom** [comment]
I am using the one in Github:
![image](https://github.com/ariacom/Seal-Report/assets/12451331/f640507b-3da1-4567-aaa8-f22f284571d2)

**Comment by xinyueyuanAmy** [comment]
Thanks.It has been resolved.
