### ISSUE TITLE
SQL server schema and 'special' name handling

### ISSUE THREAD

**Issue by goblinc** [ariacom/Seal-Report#11]
When using the report designer with a database that has multiple schemas, pulling tables into the model does not retain the schema of the table.  In addition, when you check the SQL generated, as well as the schema being missing, table and/or column names are not wrapped in square brackets.  

The result being that if any columns have 'special' names (eg. name, rule, etc) or the table is a member of a schema, the generated SQL is invalid.

An example of the invalid generated SQL would be (real example from a database that I'm testing Seal-Report against):

```
SELECT
  Tenant.TenantName AS C0,
  Parameters.Rule AS C1,
  Site.LocalReadingTime AS C2,
  Sum(Site.FeedDensityRollingAvg) AS C3
FROM 
(Tenant INNER JOIN 
(Parameters INNER JOIN Site
 ON Parameters.SiteId = Site.SiteId)
 ON Tenant.TenantId = Parameters.TenantId)
GROUP BY Tenant.TenantName,Parameters.SiteName,Site.LocalReadingTime
ORDER BY Tenant.TenantName ASC,Parameters.SiteName ASC,Site.LocalReadingTime ASC,Sum(Site.FeedDensityRollingAvg) ASC
```

This is the corrected SQL (after copy & pasting into SSMS and resolving the errors):

```
SELECT
  Tenant.TenantName AS C0,
  Parameters.[Rule] AS C1,
  Site.LocalReadingTime AS C2,
  Sum(Site.FeedDensityRollingAvg) AS C3
FROM 
(Users.Tenant INNER JOIN 
(Site.Parameters INNER JOIN Readings.Site
 ON Parameters.SiteId = Site.SiteId)
 ON Tenant.TenantId = Parameters.TenantId)
GROUP BY Tenant.TenantName,Parameters.SiteName,Site.LocalReadingTime
ORDER BY Tenant.TenantName ASC,Parameters.SiteName ASC,Site.LocalReadingTime ASC,Sum(Site.FeedDensityRollingAvg) ASC
```

**Comment by ariacom** [comment]
Yes, we could enhance this, 
for columns having special names, you can easily add the square brackets in the column definition of your source, it won't be long.

**Comment by SilverMountainSoftware** [comment]
I also need this to be able to run it. I would make this as a bug because there are lots of common table names (like in our situation, "Case") which are "special" and need the square brackets.

**Comment by ariacom** [comment]
ok, we will check if we can do this for the 4.1
