### ISSUE TITLE
SWExecuteReportToResult to export CSV results

### ISSUE THREAD

**Issue by D3r3k** [ariacom/Seal-Report#13]
Hi guys,

Can the above method on the REST service return CSV results? According to the documentation, it can do HTML, Print, PDF and Excel (using the converter) - but I need it to return CSV for a specific project.

Thanks,
D

**Comment by ariacom** [comment]
Yes, you are right the CSV has been forgotten... I will try to update this in the incoming 4.0.1

**Comment by D3r3k** [comment]
Thanks that would be awesome. Do you have any idea of when 4.0.1 will be released?

**Comment by ariacom** [comment]
soon, hopefully this friday

**Comment by D3r3k** [comment]
Brilliant. Thanks very much - you have no idea how useful this will be for us.

**Comment by ariacom** [comment]
4.0.1 is just released, thank you to check it.
