### ISSUE TITLE
Left Out Join Issue

### ISSUE THREAD

**Issue by xutao650** [ariacom/Seal-Report#14]
Hi! It's nice for you to provide this excelent tool for us! I got a problem as below:
Table "HoldInfo" has 3 columns "Reason" , "TxnUserID" while "TxnUserID" and "HoldToUserID" can be null.
Table "UserInfo" has 2 columns "UserID" and "UserName".  I want to get.a datatable like "Reason","Txn User Name","HoldUserName". But the generated sql is not correct : SELECT ... FROM (UserInfo1 Left out join (HoldInfo Left Outer Join UserInfo 2 on. .) on. ..),So I can not get the datas whose txnuserid is null.
I.have config 3 tables "HoldInfo","UserInfo1","UserInfo2" and 2 left out joins in designer.
Can you help to fix it!

**Comment by ariacom** [comment]
Hello, can you make a sample in Northwind, and repost the question using http://forum.sealreport.org/
You can attach your report definition.
Thanks.

**Comment by xutao650** [comment]
Thank you for your reply! I will post it in the forum next Monday as I have no computer beside me now! Thank you!
