### ISSUE TITLE
Issue: Generated SQL for where on datetime type not using custom format

### ISSUE THREAD

**Issue by brucod** [ariacom/Seal-Report#16]
First, thanks for the software!  I'm really enjoying using it.  You can tell you put a ton of thought into designing it to be dynamic and customizable.  Kudos

I'm trying to create a report in v4.0.1.0 that will query results based solely on date as a restriction.  The field, named 'date_time', is a standard MSSQL datetime type.  I'm using a custom SQL on the restriction to convert the records to yyyy-MM-dd format using convert(char(10), date_time, 120).  I set a custom format for the same.  The restriction selector is displaying the custom format properly; however, the generated SQL statement is not using this custom format to only query for the date.  It appends the time.  I tried the pre-defined format types of short and long dates with the same result - the time is appended.

Below is a screenshot of the restriction with the options I've entered and the generated SQL statement:

![seal_report_designer_issue_1](https://user-images.githubusercontent.com/29108767/41796449-37b059c8-762c-11e8-9389-4516bfb872e2.png)

Below is screenshot showing one date_time field and converted field as used in the the custom SQL option.  At the bottom of the screenshot, is an example of the desired SQL statement/results:

![seal_report_designer_issue_2](https://user-images.githubusercontent.com/29108767/41796450-37d2ad5c-762c-11e8-9018-5b8e9f0c4a48.png)

Thanks!

Edit for clarity:  The custom SQL conversion is how the product handles this internally, which is painfully slow.  In the final report, I'll most likely use no custom SQL and yyyyMMdd custom format for quicker execution and to be syntactically correct.

**Comment by ariacom** [comment]
Normally Date Time restrictions depends on the format specified, it checks if there is time or not.
In your sample you can not convert your DateTime in a Char, and let the type of the restriction as DateTime, it makes no sense. If the result is a char, you must set the type to Text.
It is always bad for performances to convert the datetime to char if it is a restriction.

**Comment by brucod** [comment]
Thank you for the reply and support.  In hindsight, I should made the 'Edit for clarity' section in my last post more visible.  For benchmarking, I was setting up like-for-like reports in Seal Reports vs the application's reporting system using the same SQL syntax it does.  This isn't what I would have used.  I can see where using this as an example caused confusion.  Please ignore the previous example.

Hopefully the screenshots below better illustrate the issue that I'm seeing.  In Seal Reports, I'm wanting it to only run reports for a date ranges so times do not have to be selected by the user or dealt with in SQL.  

Using [this example](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/between-transact-sql?view=sql-server-2017#d-using-between-with-datetime-values) from Microsoft, I can use 'between yyyyMMdd and yyyyMMdd'.  If you look at the green highlighted portions and text, you'll notice the restrictions is displaying the proper custom format I specified 'yyyyMMdd'; however, the generated SQL highlighted in red is not honoring this format and defaulting to 'yyyy-MM-dd hh:mm:ss'.  I've tried many custom formats and the results are always the same.  I would like the generated SQL to use the custom format specified 'yyyyMMdd'

![seal_report_designer_issue_3](https://user-images.githubusercontent.com/29108767/42396874-3bae1404-8129-11e8-8b79-c2ba83b14c68.png)


Below is working SQL example from MS SSMS showing what I would like Seal Reports to generate based on the custom format specified:

![seal_report_designer_issue_4](https://user-images.githubusercontent.com/29108767/42396876-3bc7a6d0-8129-11e8-8aa1-1c3fb0121748.png)

**Comment by ariacom** [comment]
Actually the custom format is only for the display...
The format used to generate the SQL is defined in the data source connection:
In the TreeView, Select your Source->Connection then edit the property 'Date Time format'
This may be changed dynamically using Razor Scripts...

**Comment by brucod** [comment]
Okay, thanks for the reply and support.  I don't want to edit the format globally since there will be a need to run other reports based on certain time frames less than one day (Last 15 mins, 30 mins, 60 mins, 90 mins, etc).  I'll look into implementing this with Razor Scripts for each report since it will be different for each.
