### ISSUE TITLE
Reserved word column names genereate an error.

### ISSUE THREAD

**Issue by jafin** [ariacom/Seal-Report#2]
For MSSQL, tables with reserved words (ie column called 'Order') will throw an error on the generated SQL.  It would be useful if the native database delimiters could be used on columns (ie for MSQL square brackets).  

Workaround is to set the Custom SQL value to [Order] (in this example) to get a correct SQL query syntax.

**Comment by ariacom** [comment]
As you say for MSSQL, you can use keywords for table or columns names using square brackets...
So just change in your data source the table name to [order] and it will work for all generated SQL...
