### ISSUE TITLE
Build source problem, SWIDashboard missing

### ISSUE THREAD

**Issue by foldax** [ariacom/Seal-Report#20]
I cannot build head revision from source
In file swi-main.ts i get urecognized type SWIDashboard
error message is:
Cannot find name 'SWIDashboard'. Did you mean 'hasDashboard'? swi-main.ts	144	
TS2552	(TS) Cannot find name 'SWIDashboard'. Did you mean 'hasDashboard'?

**Comment by ariacom** [comment]
You have to use Release distributions as the current version is under dev....

**Comment by foldax** [comment]
ok, thanks
