### ISSUE TITLE
Forum registration error

### ISSUE THREAD

**Issue by netesheng** [ariacom/Seal-Report#21]
Forum registration error
Hello, after clicking Register on the forum to agree to the agreement, an error page appears.

![QQ截图20190327115705](https://user-images.githubusercontent.com/9253891/55049515-82656180-5087-11e9-8d9b-dff7deeb41ea.jpg)

**Comment by ariacom** [comment]
Hi, can you check if you still have the error as we have new registered user and posts....
Thank to let me know.

**Comment by ariacom** [comment]
Error still here, we are checking...

**Comment by ariacom** [comment]
This has been fixed on  https://sealreport.org/forum, please confirm and close. Thank you.

**Comment by netesheng** [comment]
Thank‘s！
