### ISSUE TITLE
Why are there some files missing in code

### ISSUE THREAD

**Issue by Quttia** [ariacom/Seal-Report#23]
There are files structure in SealWebServer.csproj
but no 'Images' folder in code

![image](https://user-images.githubusercontent.com/26808114/60096756-5e97e180-9784-11e9-9455-01cd30a7b9cd.png)
![image](https://user-images.githubusercontent.com/26808114/60144535-59bf4600-97f5-11e9-917a-f51f7b98c11d.png)

**Comment by ariacom** [comment]
Thank you, the project has just been update.
