### ISSUE TITLE
How to add support for Excel 64-bit（ODBC Drivers ）

### ISSUE THREAD

**Issue by liuxp311** [ariacom/Seal-Report#30]
How to add support for Excel 64-bit？

**Comment by ariacom** [comment]
You need to download and install the Microsoft 64bit driver.
https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=13255

**Comment by liuxp311** [comment]
My computer has 64bit Office2016 installed. This report system does not support Excel and Access?
![image](https://user-images.githubusercontent.com/52898631/71135428-8ac88280-223c-11ea-

![image](https://user-images.githubusercontent.com/52898631/71135516-cd8a5a80-223c-11ea-884c-e4f99ec2c073.png)

**Comment by liuxp311** [comment]
08:53:04 Starting execution of '32-Task Load Excel Table in SQLServer Database' (No security context)...
08:53:04 Executing report tasks...
08:53:04 Starting task 'Load table'
08:53:04 Starting task with connection 'connection'
08:53:04 Executing Script...
08:53:04 Checking for new version of 'C:\Seal-Report-5.0\Repository\Databases\databank.worldbank.org_health_population.xlsx'
08:53:04 File has changed, reload it
08:53:04 Starting Loading Excel Table from 'C:\Seal-Report-5.0\Repository\Databases\databank.worldbank.org_health_population.xlsx'
08:53:04 Error in task 'Load table': ERROR [IM002] [Microsoft][ODBC 驱动程序管理器] 未发现数据源名称并且未指定默认驱动程序

08:53:04 Ending task 'Load table'

08:53:04 Rendering report...

**Comment by ariacom** [comment]
You need Seal Report 64bit distribution, then the ODBC driver 64bit (I do not know if it is installed with office) and finally check the data source connection string that may be adapted as it depends on the driver you have installed...

**Comment by liuxp311** [comment]
My computer has 64-bit ODBC installed, but the EXCEL file is used as a data source, and the program is published incorrectly
