### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Maxiz80** [ariacom/Seal-Report#35]
Hi.
I've installed the open source version.
Everything is ok if I go to reports and load it.
What I'm not able to do is to show a widget in the dashboard page.
I don't know that I'm doing bad.
No message or error and no log to check

**Comment by ariacom** [comment]
Did you check this: https://sealreport.org/Reports.cshtml#lineViews_2
One the widget published (by saving the Report), the Web Report Server has to be restarted to load and propose the new Widgets.

**Comment by Maxiz80** [comment]
Same result.
The report (srex) get elaborated and return a NVD3 graph correctly, so I presume that all is working correctly (data is collected from local SQL Server).
![image](https://user-images.githubusercontent.com/14159717/75260396-da519e80-57e9-11ea-8a8f-6eb018b8ce70.png)
and that's my sdax file content:
<?xml version="1.0" encoding="utf-8" ?>
<Dashboard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Name>A Dashboard Name</Name>
<Items>
   <DashboardItem><WidgetGUID>bde72f14-c84c-4866-945c-4c546d1b04fd</WidgetGUID></DashboardItem>
</Items>
</Dashboard>        

What am I doing wrong?
And why "General" and "Sales" keep geting created under Dasboards folder even if I delete them?
My suspect is that i've to configure something else.
And it's really difficult if you can't use Dashboard Designer...

**Comment by ariacom** [comment]
General and Sales are created because they are configured in the current dashboard security:
Server Manager then Menu Configure Web Security (CTRL + W), then 
Security Groups, edit the Default Group and check the Dashboord Folders in the Dashboard Security.

You may also debug/understand from your browser: CTRL + F12, then check the Network Request to see if you can see your Widget GUID....

**Comment by Maxiz80** [comment]
Tryed but I don't know where I should look at.



[NetworkData.zip](https://github.com/ariacom/Seal-Report/files/4251064/NetworkData.zip)

**Comment by Maxiz80** [comment]
Tryed but I don't know where I should look at.



[NetworkData.zip](https://github.com/ariacom/Seal-Report/files/4251064/NetworkData.zip)

**Comment by Maxiz80** [comment]
> General and Sales are created because they are configured in the current dashboard security:
> Server Manager then Menu Configure Web Security (CTRL + W), then
> Security Groups, edit the Default Group and check the Dashboord Folders in the Dashboard Security.
> 
> You may also debug/understand from your browser: CTRL + F12, then check the Network Request to see if you can see your Widget GUID....

Anyway if I don't find it how should I need to proceed?

**Comment by Maxiz80** [comment]
I've found a way.
Sincerly I don't remember how since it's a result of hours of test.
But you guide is missing a lot of piece and instructions.
It's like when you ask an information for a place and you receive as answer
Go straight for around 200-500mt, turn left and after 400-800mt and so on.
Anyway i've another question.
This is the sdax file that I'm using. WidgetGUID is clear. But if I remove the "<GUID>" it stop to work
WHY? How is it generated or validated?
<?xml version="1.0" encoding="utf-8"?>
<Dashboard xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<GUID>ac1b36b8-d8d7-42ac-a11f-a855741da875</GUID>
<Name>S4B</Name>
<Items>
<DashboardItem><WidgetGUID>92746b0e-b240-4d9d-9d92-467397594e90</WidgetGUID></DashboardItem>
</Items>
</Dashboard>

**Comment by ariacom** [comment]
I updated the documentation at https://sealreport.org/Reports#lineViews_2
