### ISSUE TITLE
Error in report building when odbc connection is used

### ISSUE THREAD

**Issue by iskanderror** [ariacom/Seal-Report#40]
Hello.
Thank you for youur work.

There is an exception ***The connection string is not defined for this Model.*** when I try to build a report using odbc connection.

It looks like **Connection.OdbcConnectionString** check is missing in the function **Seal.Model.ReportModel.FillResultTable()** in the **SealLibrary**
![Screenshot_1](https://user-images.githubusercontent.com/55435119/78125759-e9e88680-742a-11ea-9915-b2c060fb3665.jpg)

**Comment by ariacom** [comment]
Thank, I got the error, I made just the fix in ReportModel.cs
                    if (string.IsNullOrEmpty(Connection.FullConnectionString)) throw new Exception("The connection string is not defined for this Model.");

it is in github right now
