### ISSUE TITLE
Future release: Should we keep the 32bit distribution and Northwind demonstration ?

### ISSUE THREAD

**Issue by ariacom** [ariacom/Seal-Report#41]
Hi, in the near future, we are considering to give up the Northwind MS Access database and migrate the demonstration reports to SQLServer (with a data source pointing to a demo database in the cloud)...
Thus, is the 32bit distribution of Seal Report still relevant for the future ? Are you using it ?

Thanks to share your opinions...

**Comment by jortorri** [comment]
We think that today doesn't have so much sense to keep the 32bit version nor the Northwind MSAccess demo. A MS SQL database in Azure or similar could be a good option for the demo. This way, if in the future is decided to create Analysis Services sources, that could be a very interesting improvement regarding data analysis point of view, it will be quite easier.
