### ISSUE TITLE
Sub-report

### ISSUE THREAD

**Issue by bbsaad** [ariacom/Seal-Report#42]
I have installed the latest version of SealReport which is 5.5. I am trying to create sub-report from Report Designer tool but I am getting this error "Unable to create the detail report. Please save the data source first...". I'm not sure what it is asking specifically but I think I have saved the data source. I did try an alternative by creating a sub-report from Server Manager tool. But when I try to link with an existing sub-report, it give this error - "Unable to add this sub-report: The report doesn't contain any restriction." I double check that it does contain restriction. I have tried to similar thing with Northwind Database but I'm getting the same issues. I tried to link Customer.Customer ID with a sub-report Customer Details that contains Customer ID as restriction with Prompt at execution. It would be really helpful if you can guide me or help out in this matter.

**Comment by ariacom** [comment]
Yes, normally the Data Source has to be saved before creating the Detail Report...
I recommend to Stop/Start the Server Manager and Report Designer to have a clean situation where you can eventually add/create your Sub-Report...
This may be enhanced in future version...

**Comment by bbsaad** [comment]
Can you advise me how to stop/start server manager and report designer?

**Comment by ariacom** [comment]
Just save the Data Source, close/exit the Server Manager manager and re-run it...
