### ISSUE TITLE
Linux hosting with .NET core 5

### ISSUE THREAD

**Issue by weedkiller** [ariacom/Seal-Report#49]
Hello, quick couple things, I am trying to run it on Linux natively or test separately on docker. On the help page I was looking for installation guide and setup, but it said .net 4.7

- [ ] 1. is this .NET Core 5.1 I would like to try it on Linux.
- [ ] 2. would be helpful if there was a docker image.

**Comment by ariacom** [comment]
SR has not migrating to .Net Core 5, this will come in a future release, 
for the moment you have to use .Net Core 3.1 for linux deployment.

**Comment by weedkiller** [comment]
thanks, btw very nice job ! 🥇

**Comment by weedkiller** [comment]
FYI -- I was able to update to 4.8 (many bug fixes & speed) & update the nugets... seems faster
