### ISSUE TITLE
Is there a plan to support. NET Core

### ISSUE THREAD

**Issue by geffzhang** [ariacom/Seal-Report#5]
SEAL report is great, there is no plan to support. NET core, easy to run on Linux

**Comment by ariacom** [comment]
Yes could be great to support .Net Core... but no plan to do it so far as no customer or sponsor,
I added this on the feature requested at [http://forum.sealreport.org/default.aspx?g=posts&m=650#post650](http://forum.sealreport.org/default.aspx?g=posts&m=650#post650)

**Comment by MetSystem** [comment]
net core3.1

**Comment by ariacom** [comment]
still no customer or sponsor for this...

**Comment by ariacom** [comment]
A beta 5.5 has been published with a first NETCore distribution...
Thank you to check and comment...

**Comment by huazhenhz** [comment]
We are expecting the new version based on .NET Core...
