### ISSUE TITLE
When to join support MySql.Data

### ISSUE THREAD

**Issue by zhoujunhe** [ariacom/Seal-Report#54]
Hello, when will it be added to oracle's official MySql.Data driver?

**Comment by ariacom** [comment]
No plan to do that so far, why don't you use the odbc driver ? do you needs special features ?

**Comment by zhoujunhe** [comment]
I have already added the MySql.Data code, and I want to contribute this part of the code.

**Comment by ariacom** [comment]
Hi,  you may make a Pull Request to add, we will check it, thanks.
