### ISSUE TITLE
Can sealrepoty used the jquery

### ISSUE THREAD

**Issue by yens01** [ariacom/Seal-Report#57]
I want to used jquery 
but i used the js 
the report can't saw
want wrong on it

src='http://cdn.staticfile.org/jquery/2.1.1/jquery.min.js'></script>
<script type="text/javascript" src="http://cdn.staticfile.org/jquery.qrcode/1.0/jquery.qrcode.min.js"

https://i.imgur.com/uP1EXp2.png
https://i.imgur.com/xIeVy2E.png

**Comment by ariacom** [comment]
You do not need to include jquery as it is already included in
        <link type='text/css' href='file:///C:\_dev\Seal-Report\Repository\Views\Content\datatables.min.css' rel='stylesheet'/>
