### ISSUE TITLE
How to automate monthly report generation

### ISSUE THREAD

**Issue by onaxsys** [ariacom/Seal-Report#7]
HI, is there a way to run seal report on a Windows Server 2012 to generate multiple reports from SQl Server database on a monthly basis.
I ask this because the only implementations I've seen from the available online documentations are through the **Report Designer** and using with a web application project.
Please an urgent respond would be appreciated.
Thanks.

**Comment by ariacom** [comment]
Yes, the task scheduler can do that for you, it relies on the Windows Scheduler, just create an output and a schedule in your report using the Report Designer.

**Comment by onaefe** [comment]
okay. thanks for the swift response. So from what you just wrote, I assume the seal report along side the Report Designer have to be installed on the server; right?

**Comment by ariacom** [comment]
Yes, it is better to install the Server Manager, Report Designer to configure your Server and Reports...and the Task Scheduler to execute them in batch.
