### ISSUE TITLE
Microsoft.AspNetCore.Razor.Language 2.2.0 -> 6.0.2

### ISSUE THREAD

**Issue by pacharbit** [ariacom/Seal-Report#72]
Hi, we are facing a DLL hell in our project, one of our dependency brings Microsoft.AspNetCore.Razor.Language 6.0.2, and SealReport brings Microsoft.AspNetCore.Razor.Language 2.2.0. 
Is it planned to update this component, or do you know a fork of SealReport that would implement Razor.Language 6.0.2 ?
Thanks a lot 
Pierre

**Comment by ariacom** [comment]
I just made the move (Microsoft.AspNetCore.Razor.Language" Version="6.0.8"), if you get the last source code, you might validate the change...
thanks.

**Comment by pacharbit** [comment]
Wow thanks so much for that ! we test the change and come back to you ;)

**Comment by pacharbit** [comment]
Hi, we are looking forward to integrate this Razor.Language version update in our developments to test it. 
Do you know when the next Seal Report build will be available? 
Thank you very much for your time, sorry for being in such a hurry, this issue is very blocking for us and we have to consider a plan B if we can't integrate your fix.
Best regards
Pierre

**Comment by ariacom** [comment]
No, no release planned this year I guess...you cannot make the build on your own ?

**Comment by pacharbit** [comment]
Thanks, that would be great ! have a nice day

**Comment by pacharbit** [comment]
Hi, thanks for this new version 6.7.0 ! 
We tried to integrate it in our project, but we faced some issues.
- The Razor.Language dll that we get with v.6.7.0 is v.2.2.0 (from RazorEngine.NetCore 2.2.4), but we were expecting an upgrade (Razor.Language 6.0.9) according to our last exchanges and this commit: https://github.com/ariacom/Seal-Report/commit/a6dec89f5681ef4a1e6e8ecc2e8d455f2a31c16b
Maybe we are making a mistake somewhere in the import ? 

- Before the release of v6.7.0, we have been able to compile a version of SealReport, integrating your changes following our exchanges. However this error appeared when calling the method Seal.Model.Report.Create(_repository);

  Message: 
System.Exception : Unable to find view template named 'Model'

  Procedure call tree: 
RepositoryServer.GetViewTemplate(String name)
Report.AddView(String templateName)
Report.Create(Repository repository)
ReportBuilderBase.CreateReport() line 238
ReportBuilderDirector.BuildReport(IReportBuilder builder) line 16
ReportBuilderTests.GenerateCSVResult_TestTableReportBuilder_DataExportInCSVFile() line 20

Do you know where this error comes from? 

Thank you very much, have a nice day
Pierre

**Comment by ariacom** [comment]
Hi, the dependencies of the RazorEngine project are:
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Runtime" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
    <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup> 

The second error you mention appears when the Repository is not set (it cannot find the Model template in the Views directory). Check that the repository location is correct.

**Comment by pacharbit** [comment]
Hello, thanks for your answer, 
I checked the Seal Report package we get from nuget.org, it comes with RazorEngine >= 2.2.3.6. Visual Studio will take the v.2.2.4 just above, with RazorLanguage v.2.2.0.

![2022-11-04_09h15_42](https://user-images.githubusercontent.com/76956961/199925227-656a37b9-25d9-4c7b-a1b5-83580705e798.png)

Our project that hosts Seal Report is a net6.0 one.  Maybe we can force a dependency to RazorEngine 3 or above ?

**Comment by ariacom** [comment]
RazorEngine.NetCore is a local project compiled in the Seal solution. The version 2.2.3.6 is just in the project file,
   RootNamespace>RazorEngine</RootNamespace>
    AssemblyName>RazorEngine.NetCore</AssemblyName>
    PackageTags>RazorEngine;aspnetcore;NetCore</PackageTags>
    Authors>Connie Yau, HermanHo, Fouad Messaia,Zuliang Liu(China)</Authors>
    Description>Fork from https://github.com/hermanho/RazorEngine, But Fixed Bug that Razor string does not support @using and @inherits and @functions and @section, etc. </Description>
    RepositoryType>git</RepositoryType>
    Version>2.2.3.6</Version>
    Copyright>RazorEngine Copyright © RazorEngine Project 2011-2018</Copyright>

the true dependencies are 
PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
PackageReference Include="Microsoft.AspNetCore.Razor.Runtime" Version="2.2.0" />
PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.9" />
PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
PackageReference Include="Microsoft.CSharp" Version="4.7.0" />

if you have problems, you might consider to include the Seal Library in your project (it is open source)

**Comment by ariacom** [comment]
perhaps there is is mismatch during the nutget package generation, it wants to depends on RazorEngine.NetCore project...
we will check in a future release if we can stick again to the original package.

**Comment by pacharbit** [comment]
Dear Ariacom, we are facing an issue with the last nuget package available on nuget.org.
SealLibrary 6.7.2 comes needs RazorEngine 6.7.2, but this version doesn't exist on the nuget.org server. 
Can you push this nuget ? 
Thanks ! 
Pierre

**Comment by ariacom** [comment]
yes, the dependency is incorrect, we hope to fix this soon with the 6.8

**Comment by pacharbit** [comment]
Thanks

**Comment by ariacom** [comment]
hello, the 6.8 is published, and it comes with the RazorEngine package.

**Comment by pacharbit** [comment]
Thanks a lot, this will help ! 
Best regards
Pierre
