### ISSUE TITLE
When Using Store Proc with Enum Id with in () this braces 

### ISSUE THREAD

**Issue by incitesol** [ariacom/Seal-Report#78]
class name : ReportRestriction

Method Name :  void BuildTexts()

string.Format("({0})", (HasValue ? EnumSQLValue : "NULL"));

Error while executing Store Proc

**Comment by ariacom** [comment]
I think that restrictions for enum will not work for Stored Procedures, should be an enhamcement to do that

**Comment by incitesol** [comment]
Oh!, but it works for me if I changed the code.

from
_SQLText = string.Format("({0})", (HasValue ? EnumSQLValue : "NULL"));

To,
_SQLText = string.Format("{0}", (HasValue ? EnumSQLValue : "NULL"));

Any Impact if I do so?

Thanks,
Sekhar Gadisala

**Comment by ariacom** [comment]
It should work if you select only one value in your enum, but I guess this will not work if there are several values...
Can you try ?
If so, one idea could be to remove the () if the enum has only one value:
EnumValues.Count == 1

**Comment by incitesol** [comment]
Yes your right,

If possible EnumValues with multiple '(2,3,4,5,6)' This makes good.

**Comment by ariacom** [comment]
as I can see, it is only used for the the operator 'Value Only', so it is better to remove the () as it can be controlled by the restriction text.
I have done the commit, it will be in the 6.9, thank you to check.

**Comment by incitesol** [comment]
_SQLText = string.Format("{0}", (HasValue ? "'" + string.Join(",", EnumValues) + "'" : "0"));

this will fix Please check from your end

**Comment by incitesol** [comment]
Eric, try to change as above...


If Enum is selected multiple values it will handle via comma separated..

'1,2,3,4,8' 

Pls look...

**Comment by ariacom** [comment]
Yes, but how will it work with an enum of type string ?
here is what we expect:
numeric 1 value -> 1
numeric several values -> 1,2,3,4,5
string or date one value -> 'aa'
string or date several values -> '''aa'',''bb'',''cc'''

in this case you have to escape the ' character, can you check this point and do pull request when you are done.
use the Helper.QuoteSingle() function to escape.

thanks

**Comment by incitesol** [comment]
**_SQLText = string.Format("{0}", (HasValue ? "'" + string.Join(",", EnumValues) + "'" : "NULL"));**

**If String**

DECLARE @enum NVARCHAR(400) = 'clothing,road,touring,bike'  
  
SELECT value  
FROM STRING_SPLIT(@enum, ',')  

**If Number**
DECLARE @enum1 NVARCHAR(400) = '202,2,3,40'  

SELECT value  
FROM STRING_SPLIT(@enum1, ',')  

These to can fulfil if we place above code, I have Tested also

**Comment by ariacom** [comment]
yes but it won't work if you have a comma or a quote in a string value, can you handle this please

**Comment by incitesol** [comment]
**_SQLText = string.Format("{0}", (HasValue ? "'" + string.Join(",", EnumValues.Select(s => s.Replace("'", "''")).ToList()) + "'" : "NULL"));**

DECLARE @enum1 NVARCHAR(400) = '1,string''s,3'''',,4'

SELECT value  
FROM STRING_SPLIT(@enum1, ',')  

I tried to raise pull request for this but i cant able to push the changes into my local branch

**Comment by ariacom** [comment]
I made a test, for me the most consistent remains:
_SQLText = HasValue ? EnumSQLValue : "NULL";

The test with northwind gives
SELECT DISTINCT
  Employees.LastName AS C0,
  Employees.EmployeeID AS C1,
  Products.CategoryID AS C2
FROM 
(Employees INNER JOIN 
(Orders INNER JOIN 
([Order Details] INNER JOIN Products
 ON Products.ProductID = [Order Details].ProductID)
 ON Orders.OrderID = [Order Details].OrderID)
 ON Employees.EmployeeID = Orders.EmployeeID)
WHERE Employees.LastName in (
'Buchanan','Callahan','Davolio'
)
AND Products.CategoryID in (
1,2,3
)
ORDER BY Employees.LastName ASC,Products.CategoryID ASC
![image](https://user-images.githubusercontent.com/12451331/221844335-b91ee08c-f838-431c-ab8a-1a70183ca15a.png)

can you make scenario how you are using this with a sample report based on northwind ?

**Comment by ariacom** [comment]
ok, I will enhance the report sample 401-SQL Server Stored Procedure with parameters to make it work for enums of type String and Numeric

**Comment by ariacom** [comment]
Ok, I have committed you changes, with dedicated tests in the report '401-SQL Server Stored Procedure with parameters'
Thank you to check.
