### ISSUE TITLE
Webserver Application not showing report

### ISSUE THREAD

**Issue by onaxsys** [ariacom/Seal-Report#8]
Hello,

I've recently begun using seal report and it seems like a great reporting tool. I however seem to constantly have a challenge with the website published on IIS from the Seal Server manager. Instead of showing the reports which I created with the server manager and designer, it just keeps showing the default seal demo reports.
Is there anywhere that I need to update a connection string or is there something not being done right? An urgent response would be really appreciated.
thanks.

**Comment by ariacom** [comment]
Hi, the reports published and showed by the Web Report Server are only located in the sub-folder of your 'Reports' repository (normally C:\ProgramData\Seal Report Repository\Reports), so just copy the reports you want to publish with the Web Report Server in that location...

**Comment by onadebi** [comment]
okay, so I did as you said and it woks fine, but one issue I noticed; don't know if its a bug.
I created a folder in the Reports (normally C:\ProgramData\Seal Report Repository\Reports) folder where I stored my report. I then tried adding another report by creating another model in Report Designer which I saved As a different name to the same reports folder.
The problem now is that, while I can see and click on the report link on web report Server, it still outputs exactly the same report as the one previously created. So, I have two reports bearing different name, desighned to show different records but nonetheless showing exactly the same report.

pls help.

**Comment by ariacom** [comment]
The repository location is done per installation...
You have to be consistent in all you config files for the Report Designer, Server Manager and Web Report Server.
Please check this post: http://forum.sealreport.org/default.aspx?g=posts&t=91#post177

Note also that you may experienced rights problem, I recommend to run your Report Designer and Server Manager in Administrator Mode.
