### ISSUE TITLE
SealWebServer Project is not running

### ISSUE THREAD

**Issue by devendarpilli** [ariacom/Seal-Report#9]
Hello,
I am running the Project using SealWebServer as Start Up Project. But I keep on getting error related to TypeScript.Tasks.CheckFileSystemCaseSensitive. I updated all the packages and tried everything I could. Please help me how to get rid of that error. For your clear understanding I am copying the complete error below.

The "TypeScript.Tasks.CheckFileSystemCaseSensitive" task could not be loaded from the assembly D:\DashBoards\Seal-Report-master\Projects\packages\Microsoft.TypeScript.MSBuild.2.7.2\build\\..\tools\net45\TypeScript.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Thanks.

**Comment by ariacom** [comment]
Hi, actually I do not know this error, 
the current version is in alpha and it will change a lot soon, if you want a more reliable version (which should compile), I recommend to use the 3.4 release, not the current master.

**Comment by devendarpilli** [comment]
Yes. I thought of the same and tried the 3.4 version too. I am getting a parse error message says Could not load type 'SealWebServer.MvcApplication'. 

<%@ Application Codebehind="Global.asax.cs" Inherits="SealWebServer.MvcApplication" Language="C#" %>
--
Do you have any idea of this one? 
Please help.

Thanks.
